[workspace]
resolver = "2"
members = [
    "crates/editor-core",
    "crates/editor-text",
    "crates/gerber-io",
    "crates/editor-service",
    "crates/editor-app",
    "crates/rcam-project",
]

[workspace.package]
edition = "2024"
rust-version = "1.89"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
editor-text = { path = "crates/editor-text" }
editor-core = { path = "crates/editor-core" }
gerber-io = { path = "crates/gerber-io" }
editor-service = { path = "crates/editor-service" }
rcam-project = { path = "crates/rcam-project" }
gerber_parser = "0.5.0"
gerber-types = "0.7.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["float_roundtrip"] }
bytemuck = { version = "1.25.2", features = ["derive"] }
eframe = { version = "0.33.3", default-features = false, features = ["wgpu", "default_fonts"] }
egui-wgpu = "0.33.3"
