//! Verifies the checked-in `fixtures/synthetic/s4b2/sample.rcam` (§65: a
//! public synthetic evidence artifact, generated by
//! `examples/generate_sample_fixture.rs`, never a private Gerber) still
//! decodes, validates, and demonstrates shared-definition storage.
use std::path::Path;

fn fixture_path() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/synthetic/s4b2/sample.rcam")
}

#[test]
fn sample_fixture_decodes_validates_and_shares_one_definition() {
    let bytes = std::fs::read(fixture_path()).expect(
        "fixtures/synthetic/s4b2/sample.rcam is missing; regenerate with \
         `cargo run -p rcam-project --example generate_sample_fixture`",
    );
    let project = rcam_project::decode(&bytes).unwrap();
    project.validate().unwrap();

    assert_eq!(project.format_version, rcam_project::FORMAT_VERSION);
    assert_eq!(project.block_definitions.len(), 1);
    assert_eq!(project.block_definitions[0].objects.len(), 40);
    assert_eq!(project.layers.len(), 1);
    assert_eq!(
        project.layers[0].layer.objects.len(),
        5,
        "5 shared instances, not 5*40 flattened primitives"
    );

    // Encoding it again is byte-identical (§38/§46).
    let re_encoded = rcam_project::encode_v1(&project).unwrap();
    assert_eq!(bytes, re_encoded);
}
